name: Custom SSL Check

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  custom_ssl_check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run Custom SSL Check
        run: python pearlthoughts/py-script.py
